# Generated by Django 4.0.1 on 2023-01-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_team_register_alter_register_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('age', models.PositiveIntegerField()),
                ('place_of_birth', models.CharField(max_length=255)),
                ('cities', models.CharField(max_length=255)),
                ('nominee', models.CharField(blank=True, max_length=255, null=True)),
                ('dob_nominee', models.DateField(blank=True, null=True)),
                ('age_nominee', models.PositiveIntegerField(blank=True, null=True)),
                ('nominee_relation', models.CharField(blank=True, max_length=255, null=True)),
                ('agent', models.CharField(blank=True, max_length=255, null=True)),
                ('cnic_bank_statement', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('medical_report', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('for_lady', models.CharField(blank=True, max_length=255)),
                ('employee', models.PositiveIntegerField(blank=True)),
                ('education', models.CharField(blank=True, max_length=255)),
                ('gpe_no', models.PositiveIntegerField(blank=True)),
                ('husbend_income', models.PositiveIntegerField(blank=True)),
                ('monthly_deduction', models.CharField(blank=True, max_length=255)),
                ('dol', models.DateField(blank=True)),
                ('yearly_deduction', models.CharField(blank=True, max_length=255)),
                ('disease', models.CharField(choices=[('cancer', 'Cancer'), ('diabetes', 'Diabetes'), ('heartDisease', 'Heart disease'), ('other', 'Other')], default='other', max_length=20)),
                ('disease_description', models.TextField(blank=True, null=True)),
                ('operation', models.CharField(choices=[('appendectomy', 'Appendectomy'), ('openHeartSurgery', 'Open heart surgery'), ('hipReplacementSurgery', 'Hip replacement surgery'), ('other', 'Other')], default='other', max_length=200)),
                ('operation_description', models.TextField(blank=True, null=True)),
                ('medically_examined', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('chest', models.FloatField()),
                ('abdomen', models.FloatField()),
                ('suicide', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('father_alive', models.BooleanField(default=True)),
                ('father_name', models.CharField(blank=True, max_length=100)),
                ('father_health', models.CharField(blank=True, choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=5)),
                ('father_dob', models.DateField(blank=True)),
                ('father_cause_of_death', models.CharField(blank=True, max_length=100)),
                ('father_passed_away', models.DateField(blank=True)),
                ('mother_alive', models.BooleanField(default=True)),
                ('mother_name', models.CharField(blank=True, max_length=100)),
                ('mother_health', models.CharField(blank=True, choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=5)),
                ('mother_dob', models.DateField(blank=True)),
                ('mother_cause_of_death', models.CharField(blank=True, max_length=100)),
                ('mother_passed_away', models.DateField(blank=True)),
            ],
        ),
    ]
