# Generated by Django 4.0.1 on 2023-01-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_alter_form_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='form',
            name='cities',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='form',
            name='dob',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='form',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='form',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
