# Generated by Django 4.0.1 on 2023-01-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_remove_form_abdomen_remove_form_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='form',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='form',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
