# Generated by Django 4.0.1 on 2023-01-20 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_form_address_form_email_form_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='age',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='form',
            name='age_nominee',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='cities',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='form',
            name='dob',
            field=models.DateField(blank=True, default='2001-01-22'),
        ),
        migrations.AddField(
            model_name='form',
            name='dob_nominee',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='mincome',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='form',
            name='nominee',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='nominee_relation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='operation',
            field=models.CharField(choices=[('YLY', 'YLY'), ('HLY', 'HLY'), ('QLY', 'QLY')], default='other', max_length=200),
        ),
        migrations.AddField(
            model_name='form',
            name='premium',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='form',
            name='suminsured',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='form',
            name='term',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
