# Generated by Django 4.0.1 on 2023-01-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_form_age_form_age_nominee_form_cities_form_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='nominee',
            field=models.CharField(blank=True, default='2001-01-22', max_length=255, null=True),
        ),
    ]
