# Generated by Django 4.0.1 on 2023-01-21 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_alter_form_nominee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='operation',
        ),
        migrations.RemoveField(
            model_name='form',
            name='premium',
        ),
    ]
