# Generated by Django 4.0.1 on 2023-01-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_remove_form_operation_remove_form_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='premium',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
