# Generated by Django 4.0.1 on 2023-01-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_form_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='mode',
            field=models.CharField(choices=[('yly', 'YLY'), ('hly', 'HLY'), ('qly', 'QLY')], default='other', max_length=20),
        ),
    ]
