# Generated by Django 4.0.1 on 2023-01-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_form_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='disease',
            field=models.CharField(choices=[('cancer', 'Cancer'), ('diabetes', 'Diabetes'), ('heartDisease', 'Heart disease')], default='other', max_length=20),
        ),
    ]
