# Generated by Django 4.0.1 on 2023-01-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_form_disease'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='habit',
            field=models.CharField(choices=[('tabacoo', 'Tabacoo'), ('alcohal', 'Alcohal'), ('drugs', 'Drugs')], default='other', max_length=200),
        ),
        migrations.AddField(
            model_name='form',
            name='operation',
            field=models.CharField(choices=[('Appendectomy', 'Appendectomy'), ('openHeartSurgery', 'openHeartSurgery'), ('Hip replacement surgery', 'Hip replacement surgery')], default='other', max_length=200),
        ),
        migrations.AddField(
            model_name='form',
            name='yesno',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='other', max_length=200),
        ),
        migrations.AlterField(
            model_name='form',
            name='disease',
            field=models.CharField(choices=[('cancer', 'Cancer'), ('diabetes', 'Diabetes'), ('heartDisease', 'Heart disease')], default='other', max_length=200),
        ),
        migrations.AlterField(
            model_name='form',
            name='mode',
            field=models.CharField(choices=[('yly', 'YLY'), ('hly', 'HLY'), ('qly', 'QLY')], default='other', max_length=200),
        ),
    ]
