# Generated by Django 4.0.1 on 2023-01-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_form_habit_form_operation_form_yesno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='Dfam',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='other', max_length=200),
        ),
        migrations.AddField(
            model_name='form',
            name='Medexam',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='other', max_length=200),
        ),
        migrations.AddField(
            model_name='form',
            name='Nod',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='form',
            name='Nos',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='form',
            name='abdomen',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='form',
            name='causefdeath',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='form',
            name='chest',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='form',
            name='falive',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='other', max_length=200),
        ),
        migrations.AddField(
            model_name='form',
            name='fhealth',
            field=models.CharField(choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='other', max_length=200),
        ),
        migrations.AddField(
            model_name='form',
            name='height',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='form',
            name='malive',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='other', max_length=200),
        ),
        migrations.AddField(
            model_name='form',
            name='mcd',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='form',
            name='mhealth',
            field=models.CharField(choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='other', max_length=200),
        ),
        migrations.AddField(
            model_name='form',
            name='mothername',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='form',
            name='numb',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='form',
            name='nums',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='form',
            name='suicide',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='other', max_length=200),
        ),
        migrations.AddField(
            model_name='form',
            name='weight',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
