# Generated by Django 4.0.1 on 2023-01-21 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0016_alter_form_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='img',
            field=models.ImageField(default='', upload_to='media/images'),
        ),
    ]
