# Generated by Django 4.0.1 on 2023-01-21 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0017_form_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='img',
            field=models.FileField(default='', upload_to='media/images'),
        ),
    ]
