# Generated by Django 4.0.1 on 2023-01-22 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0019_alter_form_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='img',
            new_name='file',
        ),
    ]
