# Generated by Django 4.0.1 on 2023-01-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0021_alter_form_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='payPrem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(default='', upload_to='media')),
            ],
        ),
    ]
