# Generated by Django 4.0.1 on 2023-01-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0022_payprem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='file',
            field=models.ImageField(default='', upload_to='media/'),
        ),
    ]
