# Generated by Django 4.0.1 on 2023-01-22 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0024_alter_form_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='Dfam',
        ),
        migrations.RemoveField(
            model_name='form',
            name='mhealth',
        ),
    ]
