# Generated by Django 4.0.1 on 2023-01-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0026_alter_form_medexam_alter_form_nod_alter_form_nos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payprem',
            name='file',
            field=models.FileField(default='', null=True, upload_to='media/'),
        ),
    ]
