# Generated by Django 4.1.2 on 2023-01-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamprogress',
            name='id',
        ),
        migrations.AlterField(
            model_name='teamprogress',
            name='id_p',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
