# Generated by Django 4.1.2 on 2023-01-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_remove_teamprogress_id_alter_teamprogress_id_p'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamprogress',
            name='target_sales_history',
            field=models.TextField(default='[]'),
        ),
    ]
