# Generated by Django 4.1.2 on 2023-01-23 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_teamprogress_target_sales_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='date',
            field=models.CharField(default=datetime.date(2023, 1, 23), max_length=200),
        ),
    ]
