# Generated by Django 4.1.2 on 2023-01-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_remove_form_dfam_remove_form_mhealth_form_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='payPrem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(default='', null=True, upload_to='media/')),
            ],
        ),
    ]
