# Generated by Django 4.1.2 on 2023-01-24 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_payprem'),
    ]

    operations = [
        migrations.AddField(
            model_name='payprem',
            name='date',
            field=models.CharField(default=datetime.date(2023, 1, 24), max_length=200),
        ),
        migrations.AddField(
            model_name='payprem',
            name='login_id',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
