# Generated by Django 4.1.2 on 2023-01-22 16:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('father_name', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('dob', models.DateField(blank=True, default='2001-01-22', null=True)),
                ('age', models.CharField(blank=True, max_length=255)),
                ('cities', models.CharField(blank=True, max_length=255)),
                ('nominee', models.CharField(blank=True, default='2001-01-22', max_length=255, null=True)),
                ('dob_nominee', models.DateField(blank=True, null=True)),
                ('age_nominee', models.PositiveIntegerField(blank=True, null=True)),
                ('nominee_relation', models.CharField(blank=True, max_length=255, null=True)),
                ('mincome', models.CharField(blank=True, max_length=20)),
                ('suminsured', models.CharField(blank=True, default='500000', max_length=20)),
                ('term', models.CharField(blank=True, max_length=20)),
                ('agentID', models.CharField(blank=True, max_length=200)),
                ('plan', models.CharField(choices=[('Jeevan Sathi Assurance', 'Jeevan Sathi Assurance'), ('Child Protection Assurance', 'Child Protection Assurance'), ('Wealth Builder Plan', 'Wealth Builder Plan'), ('Supplementary Covers', 'Supplementary Covers')], default='other', max_length=200)),
                ('premium', models.CharField(blank=True, max_length=20)),
                ('mode', models.CharField(choices=[('yly', 'YLY'), ('hly', 'HLY'), ('qly', 'QLY')], default='other', max_length=200)),
                ('disease', models.CharField(choices=[('cancer', 'Cancer'), ('diabetes', 'Diabetes'), ('heartDisease', 'Heart disease')], default='other', max_length=200)),
                ('operation', models.CharField(choices=[('Appendectomy', 'Appendectomy'), ('openHeartSurgery', 'openHeartSurgery'), ('Hip replacement surgery', 'Hip replacement surgery')], default='other', max_length=200)),
                ('Weak_eye_sight', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='other', max_length=200)),
                ('habit', models.CharField(choices=[('tabacoo', 'Tabacoo'), ('alcohal', 'Alcohal'), ('drugs', 'Drugs')], default='other', max_length=200)),
                ('Dfam', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='other', max_length=200)),
                ('Medexam', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='other', max_length=200)),
                ('height', models.CharField(blank=True, max_length=20)),
                ('weight', models.CharField(blank=True, max_length=20)),
                ('chest', models.CharField(blank=True, max_length=20)),
                ('abdomen', models.CharField(blank=True, max_length=20)),
                ('suicide', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='other', max_length=200)),
                ('falive', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='other', max_length=200)),
                ('fhealth', models.CharField(choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='other', max_length=200)),
                ('malive', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='other', max_length=200)),
                ('causefdeath', models.CharField(blank=True, max_length=255)),
                ('mothername', models.CharField(blank=True, max_length=255)),
                ('mhealth', models.CharField(choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='other', max_length=200)),
                ('mcd', models.CharField(blank=True, max_length=255)),
                ('numb', models.CharField(blank=True, max_length=20)),
                ('nums', models.CharField(blank=True, max_length=20)),
                ('Nos', models.CharField(blank=True, max_length=20)),
                ('Nod', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='register',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20)),
                ('user_password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='team_register',
            fields=[
                ('team_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=10)),
                ('team_email', models.CharField(max_length=20)),
                ('team_password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TeamProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_p', models.CharField(max_length=100)),
                ('team_progress', models.CharField(default=0, max_length=20)),
                ('target_sales', models.CharField(default=0, max_length=20)),
            ],
        ),
    ]
