# Generated by Django 4.1.2 on 2023-01-24 06:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_form_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='Dfam',
        ),
        migrations.RemoveField(
            model_name='form',
            name='mhealth',
        ),
        migrations.AddField(
            model_name='form',
            name='file',
            field=models.FileField(default='', null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='form',
            name='Medexam',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='other', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='Nod',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='Nos',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='abdomen',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='age',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='causefdeath',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='chest',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='cities',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='date',
            field=models.CharField(default=datetime.date(2023, 1, 24), max_length=200),
        ),
        migrations.AlterField(
            model_name='form',
            name='disease',
            field=models.CharField(choices=[('cancer', 'Cancer'), ('diabetes', 'Diabetes'), ('heartDisease', 'Heart disease')], default='other', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='falive',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='other', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='fhealth',
            field=models.CharField(choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='other', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='habit',
            field=models.CharField(choices=[('tabacoo', 'Tabacoo'), ('alcohal', 'Alcohal'), ('drugs', 'Drugs')], default='other', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='height',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='malive',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='other', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='mcd',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='mincome',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='mode',
            field=models.CharField(choices=[('yly', 'YLY'), ('hly', 'HLY'), ('qly', 'QLY')], default='other', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='mothername',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='numb',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='nums',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='operation',
            field=models.CharField(choices=[('Appendectomy', 'Appendectomy'), ('openHeartSurgery', 'openHeartSurgery'), ('Hip replacement surgery', 'Hip replacement surgery')], default='other', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='premium',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='suicide',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='other', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='weight',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
